---
latitude: 40.69631
longitude: -73.98455
map_zoom: 12
name: The Tillary Hotel
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 85 Flatbush Ave Extension
  street2: ''
  state: New York
  city: Brooklyn
  country: United States
  zip_code: '11201'
_hotel_id: THE576
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
